INFO 2019-11-27 20:27:43,927 text 11 info
ERROR 2019-11-27 20:27:43,927 text 12 error
ERROR 2019-11-27 20:30:42,987 text 12 error
INFO 2019-11-27 21:05:14,798 text 11 info
INFO 2019-11-27 21:09:17,420 text 11 info
INFO 2019-11-27 21:15:36,672 text 11 info
INFO 2019-11-27 22:08:07,542 text 11 info
WARNING 2019-11-27 22:13:32,486 base 93 Not Found: /
WARNING 2019-11-27 22:13:32,489 basehttp 124 "GET / HTTP/1.1" 404 2153
WARNING 2019-11-27 22:13:33,081 base 93 Not Found: /favicon.ico
WARNING 2019-11-27 22:13:33,082 basehttp 124 "GET /favicon.ico HTTP/1.1" 404 2204
WARNING 2019-11-27 22:13:36,446 base 93 Not Found: /favicon.ico
WARNING 2019-11-27 22:13:36,447 basehttp 124 "GET /favicon.ico HTTP/1.1" 404 2204
ERROR 2019-11-27 22:13:45,123 exception 118 Internal Server Error: /user/text/
Traceback (most recent call last):
  File "D:\zx\Virtualenvs\lf\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: __init__() takes 1 positional argument but 2 were given
ERROR 2019-11-27 22:13:45,478 basehttp 124 "GET /user/text/ HTTP/1.1" 500 67606
ERROR 2019-11-27 22:14:34,085 exception 118 Internal Server Error: /user/text/
Traceback (most recent call last):
  File "D:\zx\Virtualenvs\lf\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: __init__() takes 1 positional argument but 2 were given
ERROR 2019-11-27 22:14:34,423 basehttp 124 "GET /user/text/ HTTP/1.1" 500 67523
ERROR 2019-11-27 22:16:48,515 exception 118 Internal Server Error: /user/text/
Traceback (most recent call last):
  File "D:\zx\Virtualenvs\lf\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\django\core\handlers\base.py", line 158, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\django\core\handlers\base.py", line 156, in _get_response
    response = response.render()
  File "D:\zx\Virtualenvs\lf\lib\site-packages\django\template\response.py", line 106, in render
    self.content = self.rendered_content
  File "D:\zx\Virtualenvs\lf\lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\rest_framework\renderers.py", line 724, in render
    template = loader.get_template(self.template)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: rest_framework/api.html
ERROR 2019-11-27 22:16:48,849 basehttp 124 "GET /user/text/ HTTP/1.1" 500 87030
INFO 2019-11-27 22:20:50,250 text 11 info
INFO 2019-11-27 22:20:55,088 text 11 info
ERROR 2019-11-27 22:21:04,098 exception 118 Internal Server Error: /user/text/
Traceback (most recent call last):
  File "D:\zx\Virtualenvs\lf\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\django\core\handlers\base.py", line 158, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\django\core\handlers\base.py", line 156, in _get_response
    response = response.render()
  File "D:\zx\Virtualenvs\lf\lib\site-packages\django\template\response.py", line 106, in render
    self.content = self.rendered_content
  File "D:\zx\Virtualenvs\lf\lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\rest_framework\renderers.py", line 724, in render
    template = loader.get_template(self.template)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: rest_framework/api.html
ERROR 2019-11-27 22:21:04,448 basehttp 124 "GET /user/text/ HTTP/1.1" 500 87216
ERROR 2019-11-27 22:21:07,523 exception 118 Internal Server Error: /user/text/
Traceback (most recent call last):
  File "D:\zx\Virtualenvs\lf\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\django\core\handlers\base.py", line 158, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\django\core\handlers\base.py", line 156, in _get_response
    response = response.render()
  File "D:\zx\Virtualenvs\lf\lib\site-packages\django\template\response.py", line 106, in render
    self.content = self.rendered_content
  File "D:\zx\Virtualenvs\lf\lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\rest_framework\renderers.py", line 724, in render
    template = loader.get_template(self.template)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: rest_framework/api.html
ERROR 2019-11-27 22:21:07,588 basehttp 124 "GET /user/text/ HTTP/1.1" 500 87217
ERROR 2019-11-27 22:22:16,296 exception 118 Internal Server Error: /user/text/
Traceback (most recent call last):
  File "D:\zx\Virtualenvs\lf\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\django\core\handlers\base.py", line 158, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\django\core\handlers\base.py", line 156, in _get_response
    response = response.render()
  File "D:\zx\Virtualenvs\lf\lib\site-packages\django\template\response.py", line 106, in render
    self.content = self.rendered_content
  File "D:\zx\Virtualenvs\lf\lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\rest_framework\renderers.py", line 724, in render
    template = loader.get_template(self.template)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: rest_framework/api.html
ERROR 2019-11-27 22:22:16,370 basehttp 124 "GET /user/text/ HTTP/1.1" 500 87216
INFO 2019-11-27 22:28:27,518 basehttp 124 "GET /user/text/ HTTP/1.1" 200 4
INFO 2019-11-27 22:29:03,522 basehttp 124 "GET /user/text/ HTTP/1.1" 200 4
WARNING 2019-11-27 22:31:06,997 base 93 Not Found: /favicon.ico
WARNING 2019-11-27 22:31:06,999 basehttp 124 "GET /favicon.ico HTTP/1.1" 404 2204
WARNING 2019-11-27 22:31:07,463 base 93 Not Found: /user/test/
WARNING 2019-11-27 22:31:07,465 basehttp 124 "GET /user/test/ HTTP/1.1" 404 2253
WARNING 2019-11-27 22:31:20,771 base 93 Not Found: /
WARNING 2019-11-27 22:31:20,772 basehttp 124 "GET / HTTP/1.1" 404 2153
INFO 2019-11-27 22:41:13,380 basehttp 124 "GET /user/text/ HTTP/1.1" 200 4
INFO 2019-11-27 22:41:50,243 text 11 info
INFO 2019-11-27 22:42:04,542 basehttp 124 "GET /user/text/ HTTP/1.1" 200 4
INFO 2019-11-27 22:42:26,908 basehttp 124 "GET /user/text/ HTTP/1.1" 200 4
INFO 2019-11-27 22:43:24,634 basehttp 124 "GET /user/text/ HTTP/1.1" 200 4
INFO 2019-11-27 22:43:39,553 basehttp 124 "GET /user/text/ HTTP/1.1" 200 4
INFO 2019-11-27 22:44:11,785 basehttp 124 "GET /user/text/ HTTP/1.1" 200 4
INFO 2019-11-27 22:45:10,569 basehttp 124 "POST /user/text/ HTTP/1.1" 200 4
ERROR 2019-11-27 22:45:16,243 exception 9 <user.views.Test object at 0x0000015B4E750F28> - GET - Method "GET" not allowed.
WARNING 2019-11-27 22:45:16,244 basehttp 124 "GET /user/text/ HTTP/1.1" 405 40
INFO 2019-11-27 22:47:31,792 basehttp 124 "GET /user/text/ HTTP/1.1" 200 4
INFO 2019-11-27 22:48:18,527 basehttp 124 "GET /user/text/ HTTP/1.1" 200 4
INFO 2019-11-27 22:48:48,883 basehttp 124 "GET /user/text/ HTTP/1.1" 200 4
WARNING 2019-11-27 23:14:14,637 base 93 Not Found: /favicon.ico
WARNING 2019-11-27 23:14:14,639 basehttp 124 "GET /favicon.ico HTTP/1.1" 404 2311
INFO 2019-11-27 23:14:15,654 basehttp 124 "GET /admin/ HTTP/1.1" 302 0
INFO 2019-11-27 23:14:15,999 basehttp 124 "GET /admin/login/?next=/admin/ HTTP/1.1" 200 1857
INFO 2019-11-27 23:14:16,040 basehttp 124 "GET /static/admin/css/responsive.css HTTP/1.1" 200 17894
INFO 2019-11-27 23:14:21,103 basehttp 124 "GET /admin/login/?next=/admin/ HTTP/1.1" 200 1857
INFO 2019-11-27 23:14:30,065 basehttp 124 "GET /xadmin HTTP/1.1" 301 0
INFO 2019-11-27 23:14:30,155 basehttp 124 "GET /xadmin/ HTTP/1.1" 200 4163
INFO 2019-11-27 23:14:30,206 basehttp 124 "GET /static/xadmin/css/themes/bootstrap-xadmin.css HTTP/1.1" 200 1888
INFO 2019-11-27 23:14:30,207 basehttp 124 "GET /static/xadmin/css/xadmin.plugins.css HTTP/1.1" 200 175
INFO 2019-11-27 23:14:30,208 basehttp 124 "GET /static/xadmin/css/xadmin.responsive.css HTTP/1.1" 200 4361
INFO 2019-11-27 23:14:30,209 basehttp 124 "GET /static/xadmin/css/xadmin.main.css HTTP/1.1" 200 8376
INFO 2019-11-27 23:14:30,209 basehttp 124 "GET /static/xadmin/vendor/font-awesome/css/font-awesome.css HTTP/1.1" 200 21658
INFO 2019-11-27 23:14:30,214 basehttp 124 "GET /static/xadmin/vendor/bootstrap/css/bootstrap.css HTTP/1.1" 200 126432
INFO 2019-11-27 23:14:30,275 basehttp 124 "GET /static/xadmin/vendor/jquery-ui/jquery.ui.core.js HTTP/1.1" 200 8195
INFO 2019-11-27 23:14:30,277 basehttp 124 "GET /static/xadmin/vendor/jquery-ui/jquery.ui.sortable.js HTTP/1.1" 200 42543
INFO 2019-11-27 23:14:30,278 basehttp 124 "GET /xadmin/jsi18n/ HTTP/1.1" 200 4170
INFO 2019-11-27 23:14:30,282 basehttp 124 "GET /static/xadmin/vendor/jquery-ui/jquery.ui.widget.js HTTP/1.1" 200 15069
INFO 2019-11-27 23:14:30,283 basehttp 124 "GET /static/xadmin/vendor/jquery-ui/jquery.ui.mouse.js HTTP/1.1" 200 4561
INFO 2019-11-27 23:14:30,290 basehttp 124 "GET /static/xadmin/js/xadmin.responsive.js HTTP/1.1" 200 4165
INFO 2019-11-27 23:14:30,292 basehttp 124 "GET /static/xadmin/vendor/jquery/jquery.js HTTP/1.1" 200 240196
INFO 2019-11-27 23:14:30,319 basehttp 124 "GET /static/xadmin/vendor/bootstrap/js/bootstrap.js HTTP/1.1" 200 58327
INFO 2019-11-27 23:14:30,322 basehttp 124 "GET /static/xadmin/js/xadmin.main.js HTTP/1.1" 200 3401
INFO 2019-11-27 23:14:30,387 basehttp 124 "GET /static/xadmin/vendor/font-awesome/fonts/fontawesome-webfont.woff?v=4.0.3 HTTP/1.1" 200 44432
INFO 2019-11-27 23:14:36,879 basehttp 124 "POST /xadmin/ HTTP/1.1" 302 0
INFO 2019-11-27 23:14:37,008 basehttp 124 "GET /xadmin/ HTTP/1.1" 200 11710
INFO 2019-11-27 23:14:37,046 basehttp 124 "GET /static/xadmin/css/xadmin.page.dashboard.css HTTP/1.1" 200 790
INFO 2019-11-27 23:14:37,049 basehttp 124 "GET /static/xadmin/js/xadmin.plugin.portal.js HTTP/1.1" 200 1000
INFO 2019-11-27 23:14:37,051 basehttp 124 "GET /static/xadmin/js/xadmin.page.dashboard.js HTTP/1.1" 200 3208
INFO 2019-11-27 23:14:37,070 basehttp 124 "GET /xadmin/jsi18n/ HTTP/1.1" 200 7684
INFO 2019-11-27 23:14:43,116 basehttp 124 "GET /xadmin/user/user/ HTTP/1.1" 200 31577
INFO 2019-11-27 23:14:43,145 basehttp 124 "GET /static/xadmin/css/xadmin.form.css HTTP/1.1" 200 3763
INFO 2019-11-27 23:14:43,164 basehttp 124 "GET /static/xadmin/js/xadmin.plugin.filters.js HTTP/1.1" 200 1990
INFO 2019-11-27 23:14:43,165 basehttp 124 "GET /static/xadmin/js/xadmin.plugin.details.js HTTP/1.1" 200 2319
INFO 2019-11-27 23:14:43,167 basehttp 124 "GET /static/xadmin/js/xadmin.plugin.actions.js HTTP/1.1" 200 4198
INFO 2019-11-27 23:14:43,167 basehttp 124 "GET /static/xadmin/js/xadmin.plugin.bookmark.js HTTP/1.1" 200 529
INFO 2019-11-27 23:14:43,170 basehttp 124 "GET /static/xadmin/js/xadmin.page.list.js HTTP/1.1" 200 1105
INFO 2019-11-27 23:14:43,175 basehttp 124 "GET /static/xadmin/js/xadmin.page.form.js HTTP/1.1" 200 1948
INFO 2019-11-27 23:14:43,185 basehttp 124 "GET /xadmin/jsi18n/ HTTP/1.1" 200 7684
WARNING 2019-11-27 23:14:48,468 csrf 153 Forbidden (CSRF token missing or incorrect.): /admin/login/
WARNING 2019-11-27 23:14:48,476 basehttp 124 "POST /admin/login/?next=/admin/ HTTP/1.1" 403 2508
WARNING 2019-11-27 23:15:54,592 csrf 153 Forbidden (CSRF token missing or incorrect.): /admin/login/
WARNING 2019-11-27 23:15:54,604 basehttp 124 "POST /admin/login/?next=/admin/ HTTP/1.1" 403 2508
INFO 2019-11-27 23:15:58,916 basehttp 124 "GET /admin/ HTTP/1.1" 200 2555
INFO 2019-11-27 23:15:58,962 basehttp 124 "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
INFO 2019-11-27 23:15:58,963 basehttp 124 "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
INFO 2019-11-27 23:16:01,146 basehttp 124 "GET /admin/ HTTP/1.1" 200 2555
INFO 2019-11-27 23:16:03,280 basehttp 124 "GET /admin/auth/group/ HTTP/1.1" 200 3560
INFO 2019-11-27 23:16:03,311 basehttp 124 "GET /static/admin/css/changelists.css HTTP/1.1" 200 6170
INFO 2019-11-27 23:16:03,314 basehttp 124 "GET /static/admin/js/jquery.init.js HTTP/1.1" 200 363
INFO 2019-11-27 23:16:03,336 basehttp 124 "GET /admin/jsi18n/ HTTP/1.1" 200 7684
INFO 2019-11-27 23:16:03,338 basehttp 124 "GET /static/admin/img/search.svg HTTP/1.1" 200 458
INFO 2019-11-27 23:16:03,413 basehttp 124 "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 200 331
WARNING 2019-12-01 20:17:06,502 base 93 Not Found: /
WARNING 2019-12-01 20:17:06,516 basehttp 124 "GET / HTTP/1.1" 404 2260
WARNING 2019-12-01 20:17:06,896 base 93 Not Found: /favicon.ico
WARNING 2019-12-01 20:17:06,898 basehttp 124 "GET /favicon.ico HTTP/1.1" 404 2311
WARNING 2019-12-01 20:17:11,578 base 93 Not Found: /favicon.ico
WARNING 2019-12-01 20:17:11,579 basehttp 124 "GET /favicon.ico HTTP/1.1" 404 2311
INFO 2019-12-01 20:17:13,625 basehttp 124 "GET /xadmin HTTP/1.1" 301 0
INFO 2019-12-01 20:17:13,942 basehttp 124 "GET /xadmin/ HTTP/1.1" 200 12844
INFO 2019-12-01 20:17:14,008 basehttp 124 "GET /static/xadmin/css/xadmin.plugins.css HTTP/1.1" 200 175
INFO 2019-12-01 20:17:14,017 basehttp 124 "GET /static/xadmin/vendor/bootstrap/css/bootstrap.css HTTP/1.1" 200 126432
INFO 2019-12-01 20:17:14,023 basehttp 124 "GET /static/xadmin/css/themes/bootstrap-xadmin.css HTTP/1.1" 200 1888
INFO 2019-12-01 20:17:14,024 basehttp 124 "GET /static/xadmin/css/xadmin.responsive.css HTTP/1.1" 200 4361
INFO 2019-12-01 20:17:14,024 basehttp 124 "GET /static/xadmin/css/xadmin.page.dashboard.css HTTP/1.1" 200 790
INFO 2019-12-01 20:17:14,025 basehttp 124 "GET /static/xadmin/css/xadmin.main.css HTTP/1.1" 200 8376
INFO 2019-12-01 20:17:14,031 basehttp 124 "GET /static/xadmin/vendor/font-awesome/css/font-awesome.css HTTP/1.1" 200 21658
INFO 2019-12-01 20:17:14,087 basehttp 124 "GET /xadmin/jsi18n/ HTTP/1.1" 200 7684
INFO 2019-12-01 20:17:14,094 basehttp 124 "GET /static/xadmin/js/xadmin.responsive.js HTTP/1.1" 200 4165
INFO 2019-12-01 20:17:14,101 basehttp 124 "GET /static/xadmin/vendor/bootstrap/js/bootstrap.js HTTP/1.1" 200 58327
INFO 2019-12-01 20:17:14,106 basehttp 124 "GET /static/xadmin/js/xadmin.page.dashboard.js HTTP/1.1" 200 3208
INFO 2019-12-01 20:17:14,110 basehttp 124 "GET /static/xadmin/vendor/jquery-ui/jquery.ui.core.js HTTP/1.1" 200 8195
INFO 2019-12-01 20:17:14,114 basehttp 124 "GET /static/xadmin/vendor/jquery-ui/jquery.ui.mouse.js HTTP/1.1" 200 4561
INFO 2019-12-01 20:17:14,117 basehttp 124 "GET /static/xadmin/vendor/jquery-ui/jquery.ui.sortable.js HTTP/1.1" 200 42543
INFO 2019-12-01 20:17:14,118 basehttp 124 "GET /static/xadmin/js/xadmin.plugin.portal.js HTTP/1.1" 200 1000
INFO 2019-12-01 20:17:14,121 basehttp 124 "GET /static/xadmin/vendor/jquery-ui/jquery.ui.widget.js HTTP/1.1" 200 15069
INFO 2019-12-01 20:17:14,127 basehttp 124 "GET /static/xadmin/js/xadmin.main.js HTTP/1.1" 200 3401
INFO 2019-12-01 20:17:14,133 basehttp 124 "GET /static/xadmin/vendor/jquery/jquery.js HTTP/1.1" 200 240196
INFO 2019-12-01 20:17:14,222 basehttp 124 "GET /static/xadmin/vendor/font-awesome/fonts/fontawesome-webfont.woff?v=4.0.3 HTTP/1.1" 200 44432
INFO 2019-12-01 20:17:28,191 basehttp 124 "GET /xadmin/reversion/revision/ HTTP/1.1" 200 27414
INFO 2019-12-01 20:17:28,255 basehttp 124 "GET /static/xadmin/css/xadmin.form.css HTTP/1.1" 200 3763
INFO 2019-12-01 20:17:28,258 basehttp 124 "GET /static/xadmin/vendor/bootstrap-datepicker/css/datepicker.css HTTP/1.1" 200 10225
INFO 2019-12-01 20:17:28,267 basehttp 124 "GET /static/xadmin/vendor/selectize/selectize.css HTTP/1.1" 200 8425
INFO 2019-12-01 20:17:28,268 basehttp 124 "GET /static/xadmin/vendor/selectize/selectize.bootstrap3.css HTTP/1.1" 200 10602
INFO 2019-12-01 20:17:28,271 basehttp 124 "GET /static/xadmin/vendor/select2/select2.css HTTP/1.1" 200 19226
INFO 2019-12-01 20:17:28,272 basehttp 124 "GET /static/xadmin/js/xadmin.widget.datetime.js HTTP/1.1" 200 2979
INFO 2019-12-01 20:17:28,276 basehttp 124 "GET /static/xadmin/js/xadmin.plugin.bookmark.js HTTP/1.1" 200 529
INFO 2019-12-01 20:17:28,302 basehttp 124 "GET /static/xadmin/vendor/select2/select2_locale_zh-hans.js HTTP/1.1" 200 694
INFO 2019-12-01 20:17:28,302 basehttp 124 "GET /static/xadmin/js/xadmin.page.list.js HTTP/1.1" 200 1105
INFO 2019-12-01 20:17:28,302 basehttp 124 "GET /static/xadmin/js/xadmin.widget.select.js HTTP/1.1" 200 1344
INFO 2019-12-01 20:17:28,306 basehttp 124 "GET /static/xadmin/js/xadmin.plugin.filters.js HTTP/1.1" 200 1990
INFO 2019-12-01 20:17:28,308 basehttp 124 "GET /xadmin/jsi18n/ HTTP/1.1" 200 7684
INFO 2019-12-01 20:17:28,308 basehttp 124 "GET /static/xadmin/vendor/select2/select2.js HTTP/1.1" 200 104906
INFO 2019-12-01 20:17:28,321 basehttp 124 "GET /static/xadmin/js/xadmin.page.form.js HTTP/1.1" 200 1948
INFO 2019-12-01 20:17:28,334 basehttp 124 "GET /static/xadmin/js/xadmin.plugin.details.js HTTP/1.1" 200 2319
INFO 2019-12-01 20:17:28,337 basehttp 124 "GET /static/xadmin/vendor/bootstrap-datepicker/js/bootstrap-datepicker.js HTTP/1.1" 200 32656
INFO 2019-12-01 20:17:28,339 basehttp 124 "GET /static/xadmin/vendor/selectize/selectize.js HTTP/1.1" 200 98602
INFO 2019-12-01 20:17:30,991 basehttp 124 "GET /xadmin/user/user/ HTTP/1.1" 200 32711
INFO 2019-12-01 20:17:31,051 basehttp 124 "GET /static/xadmin/js/xadmin.plugin.actions.js HTTP/1.1" 200 4198
INFO 2019-12-01 20:17:31,052 basehttp 124 "GET /xadmin/jsi18n/ HTTP/1.1" 200 7684
INFO 2019-12-01 20:21:55,947 basehttp 124 "GET /xadmin/reversion/revision/ HTTP/1.1" 200 27414
INFO 2019-12-01 20:21:56,025 basehttp 124 "GET /xadmin/jsi18n/ HTTP/1.1" 200 7684
INFO 2019-12-01 20:21:59,658 basehttp 124 "GET /xadmin/reversion/revision/ HTTP/1.1" 200 27414
INFO 2019-12-01 20:21:59,721 basehttp 124 "GET /xadmin/jsi18n/ HTTP/1.1" 200 7684
INFO 2019-12-01 20:22:00,931 basehttp 124 "GET /xadmin/reversion/revision/ HTTP/1.1" 200 27414
INFO 2019-12-01 20:22:00,993 basehttp 124 "GET /xadmin/jsi18n/ HTTP/1.1" 200 7684
INFO 2019-12-01 20:22:07,750 basehttp 124 "GET /xadmin/home/banner/ HTTP/1.1" 200 22702
INFO 2019-12-01 20:22:07,803 basehttp 124 "GET /xadmin/jsi18n/ HTTP/1.1" 200 7684
INFO 2019-12-01 20:22:18,755 basehttp 124 "GET /xadmin/home/banner/add/ HTTP/1.1" 200 18235
INFO 2019-12-01 20:22:18,789 basehttp 124 "GET /static/xadmin/vendor/bootstrap-image-gallery/css/bootstrap-image-gallery.css HTTP/1.1" 200 3339
INFO 2019-12-01 20:22:18,800 basehttp 124 "GET /static/xadmin/vendor/bootstrap-image-gallery/js/bootstrap-image-gallery.js HTTP/1.1" 200 15611
INFO 2019-12-01 20:22:18,809 basehttp 124 "GET /static/xadmin/vendor/load-image/load-image.js HTTP/1.1" 200 8309
INFO 2019-12-01 20:22:18,821 basehttp 124 "GET /xadmin/jsi18n/ HTTP/1.1" 200 7684
INFO 2019-12-01 20:26:58,162 basehttp 124 "POST /xadmin/home/banner/add/ HTTP/1.1" 302 0
INFO 2019-12-01 20:26:58,327 basehttp 124 "GET /xadmin/home/banner/add/ HTTP/1.1" 200 18570
INFO 2019-12-01 20:26:58,388 basehttp 124 "GET /xadmin/jsi18n/ HTTP/1.1" 200 7684
INFO 2019-12-01 20:27:23,827 basehttp 124 "POST /xadmin/home/banner/add/ HTTP/1.1" 302 0
INFO 2019-12-01 20:27:23,978 basehttp 124 "GET /xadmin/home/banner/add/ HTTP/1.1" 200 18564
INFO 2019-12-01 20:27:24,035 basehttp 124 "GET /xadmin/jsi18n/ HTTP/1.1" 200 7684
INFO 2019-12-01 20:27:33,108 basehttp 124 "GET /user/text/ HTTP/1.1" 200 4
INFO 2019-12-01 20:28:00,228 basehttp 124 "POST /xadmin/home/banner/add/ HTTP/1.1" 302 0
INFO 2019-12-01 20:28:00,393 basehttp 124 "GET /xadmin/home/banner/add/ HTTP/1.1" 200 18564
INFO 2019-12-01 20:28:00,462 basehttp 124 "GET /xadmin/jsi18n/ HTTP/1.1" 200 7684
INFO 2019-12-01 20:28:31,644 basehttp 124 "POST /xadmin/home/banner/add/ HTTP/1.1" 302 0
INFO 2019-12-01 20:28:31,820 basehttp 124 "GET /xadmin/home/banner/ HTTP/1.1" 200 25829
INFO 2019-12-01 20:28:31,884 basehttp 124 "GET /xadmin/jsi18n/ HTTP/1.1" 200 7684
WARNING 2019-12-01 20:28:56,891 base 93 Not Found: /favicon.ico
WARNING 2019-12-01 20:28:56,892 basehttp 124 "GET /favicon.ico HTTP/1.1" 404 2311
WARNING 2019-12-01 20:29:01,450 base 93 Not Found: /
WARNING 2019-12-01 20:29:01,452 basehttp 124 "GET / HTTP/1.1" 404 2260
WARNING 2019-12-01 20:31:04,530 base 93 Not Found: /home/banner
WARNING 2019-12-01 20:31:04,532 basehttp 124 "GET /home/banner HTTP/1.1" 404 2470
ERROR 2019-12-01 20:31:08,781 exception 9 <home.views.BannerListAPIView object at 0x000002E7E0C64F60> - GET - Class BannerModelSerializer missing "Meta.model" attribute
ERROR 2019-12-01 20:31:08,782 basehttp 124 "GET /home/banners HTTP/1.1" 500 73
ERROR 2019-12-01 20:31:34,055 exception 9 <home.views.BannerListAPIView object at 0x000002E7E0C76A90> - GET - Class BannerModelSerializer missing "Meta.model" attribute
ERROR 2019-12-01 20:31:34,056 basehttp 124 "GET /home/banners HTTP/1.1" 500 73
INFO 2019-12-01 20:33:05,329 basehttp 124 "GET /home/banners HTTP/1.1" 200 321
WARNING 2019-12-01 20:45:50,803 base 93 Not Found: /home/banner
WARNING 2019-12-01 20:45:50,804 basehttp 124 "GET /home/banner HTTP/1.1" 404 2470
INFO 2019-12-01 20:54:02,459 basehttp 124 "GET /user/text/ HTTP/1.1" 200 4
WARNING 2019-12-01 20:54:02,463 base 93 Not Found: /home/banner
WARNING 2019-12-01 20:54:02,464 basehttp 124 "GET /home/banner HTTP/1.1" 404 2470
INFO 2019-12-01 20:54:18,999 basehttp 124 "GET /user/text/ HTTP/1.1" 200 4
WARNING 2019-12-01 20:54:19,005 base 93 Not Found: /home/banner
WARNING 2019-12-01 20:54:19,006 basehttp 124 "GET /home/banner HTTP/1.1" 404 2470
INFO 2019-12-01 20:55:06,735 basehttp 124 "GET /user/text/ HTTP/1.1" 200 4
INFO 2019-12-01 20:55:06,756 basehttp 124 "GET /home/banners HTTP/1.1" 200 321
WARNING 2019-12-01 20:55:07,192 base 93 Not Found: /home/banner/b3.png
WARNING 2019-12-01 20:55:07,199 base 93 Not Found: /home/banner/b1.png
WARNING 2019-12-01 20:55:07,203 base 93 Not Found: /home/banner/b2.png
WARNING 2019-12-01 20:55:07,211 base 93 Not Found: /home/banner/b4.jpg
WARNING 2019-12-01 20:55:07,212 basehttp 124 "GET /home/banner/b3.png HTTP/1.1" 404 2491
WARNING 2019-12-01 20:55:07,213 basehttp 124 "GET /home/banner/b1.png HTTP/1.1" 404 2491
WARNING 2019-12-01 20:55:07,214 basehttp 124 "GET /home/banner/b2.png HTTP/1.1" 404 2491
WARNING 2019-12-01 20:55:07,214 basehttp 124 "GET /home/banner/b4.jpg HTTP/1.1" 404 2491
INFO 2019-12-01 20:56:42,543 basehttp 124 "GET /user/text/ HTTP/1.1" 200 4
INFO 2019-12-01 20:56:42,562 basehttp 124 "GET /home/banners HTTP/1.1" 200 321
WARNING 2019-12-01 20:56:42,929 base 93 Not Found: /home/banner/b4.jpg
WARNING 2019-12-01 20:56:42,939 base 93 Not Found: /home/banner/b3.png
WARNING 2019-12-01 20:56:42,942 basehttp 124 "GET /home/banner/b4.jpg HTTP/1.1" 404 2491
WARNING 2019-12-01 20:56:42,948 base 93 Not Found: /home/banner/b2.png
WARNING 2019-12-01 20:56:42,953 base 93 Not Found: /home/banner/b1.png
WARNING 2019-12-01 20:56:42,954 basehttp 124 "GET /home/banner/b3.png HTTP/1.1" 404 2491
WARNING 2019-12-01 20:56:42,955 basehttp 124 "GET /home/banner/b2.png HTTP/1.1" 404 2491
WARNING 2019-12-01 20:56:42,956 basehttp 124 "GET /home/banner/b1.png HTTP/1.1" 404 2491
WARNING 2019-12-01 20:59:50,661 base 93 Not Found: /favicon.ico
WARNING 2019-12-01 20:59:50,662 basehttp 124 "GET /favicon.ico HTTP/1.1" 404 2416
INFO 2019-12-01 20:59:53,177 basehttp 124 "GET /xadmin/ HTTP/1.1" 200 12844
INFO 2019-12-01 20:59:53,261 basehttp 124 "GET /xadmin/jsi18n/ HTTP/1.1" 200 7684
INFO 2019-12-01 20:59:56,837 basehttp 124 "GET /xadmin/home/banner/ HTTP/1.1" 200 25545
INFO 2019-12-01 20:59:56,908 basehttp 124 "GET /xadmin/jsi18n/ HTTP/1.1" 200 7684
INFO 2019-12-01 21:00:09,458 basehttp 124 "POST /xadmin/home/banner/ HTTP/1.1" 200 13511
INFO 2019-12-01 21:00:09,523 basehttp 124 "GET /xadmin/jsi18n/ HTTP/1.1" 200 7684
INFO 2019-12-01 21:00:10,819 basehttp 124 "POST /xadmin/home/banner/ HTTP/1.1" 302 0
INFO 2019-12-01 21:00:10,971 basehttp 124 "GET /xadmin/home/banner/ HTTP/1.1" 200 22931
INFO 2019-12-01 21:00:11,023 basehttp 124 "GET /xadmin/jsi18n/ HTTP/1.1" 200 7684
INFO 2019-12-01 21:00:13,358 basehttp 124 "GET /xadmin/home/banner/add/ HTTP/1.1" 200 18235
INFO 2019-12-01 21:00:13,416 basehttp 124 "GET /xadmin/jsi18n/ HTTP/1.1" 200 7684
INFO 2019-12-01 21:00:27,908 basehttp 124 "POST /xadmin/home/banner/add/ HTTP/1.1" 302 0
INFO 2019-12-01 21:00:28,063 basehttp 124 "GET /xadmin/home/banner/ HTTP/1.1" 200 24734
INFO 2019-12-01 21:00:28,113 basehttp 124 "GET /xadmin/jsi18n/ HTTP/1.1" 200 7684
INFO 2019-12-01 21:00:38,432 basehttp 124 "GET /xadmin/home/banner/add/ HTTP/1.1" 200 18235
INFO 2019-12-01 21:00:38,489 basehttp 124 "GET /xadmin/jsi18n/ HTTP/1.1" 200 7684
INFO 2019-12-01 21:00:52,264 basehttp 124 "POST /xadmin/home/banner/add/ HTTP/1.1" 302 0
INFO 2019-12-01 21:00:52,437 basehttp 124 "GET /xadmin/home/banner/add/ HTTP/1.1" 200 18564
INFO 2019-12-01 21:00:52,492 basehttp 124 "GET /xadmin/jsi18n/ HTTP/1.1" 200 7684
INFO 2019-12-01 21:01:03,941 basehttp 124 "POST /xadmin/home/banner/add/ HTTP/1.1" 302 0
INFO 2019-12-01 21:01:04,094 basehttp 124 "GET /xadmin/home/banner/add/ HTTP/1.1" 200 18564
INFO 2019-12-01 21:01:04,142 basehttp 124 "GET /xadmin/jsi18n/ HTTP/1.1" 200 7684
INFO 2019-12-01 21:01:12,081 basehttp 124 "POST /xadmin/home/banner/add/ HTTP/1.1" 302 0
INFO 2019-12-01 21:01:12,230 basehttp 124 "GET /xadmin/home/banner/add/ HTTP/1.1" 200 18564
INFO 2019-12-01 21:01:12,293 basehttp 124 "GET /xadmin/jsi18n/ HTTP/1.1" 200 7684
INFO 2019-12-01 21:01:18,384 basehttp 124 "GET /user/text/ HTTP/1.1" 200 4
INFO 2019-12-01 21:01:18,410 basehttp 124 "GET /home/banners HTTP/1.1" 200 309
INFO 2019-12-01 21:01:18,869 basehttp 124 "GET /media/banner/b4.jpg HTTP/1.1" 200 17734
INFO 2019-12-01 21:01:18,888 basehttp 124 "GET /media/banner/b2.png HTTP/1.1" 200 111031
INFO 2019-12-01 21:01:18,904 basehttp 124 "GET /media/banner/b1.png HTTP/1.1" 200 772079
INFO 2019-12-01 21:01:18,910 basehttp 124 "GET /media/banner/b3.png HTTP/1.1" 200 822746
INFO 2019-12-01 21:01:19,916 basehttp 124 "GET /media/banner/b3.png HTTP/1.1" 304 0
WARNING 2019-12-01 21:45:44,872 base 93 Not Found: /
WARNING 2019-12-01 21:45:44,874 basehttp 124 "GET / HTTP/1.1" 404 2365
INFO 2019-12-01 21:46:55,562 basehttp 124 "GET /xadmin/user/user/ HTTP/1.1" 200 32711
INFO 2019-12-01 21:46:55,626 basehttp 124 "GET /xadmin/jsi18n/ HTTP/1.1" 200 7684
INFO 2019-12-01 21:46:57,929 basehttp 124 "GET /xadmin/user/user/add/ HTTP/1.1" 200 15966
INFO 2019-12-01 21:46:57,977 basehttp 124 "GET /xadmin/jsi18n/ HTTP/1.1" 200 7684
ERROR 2019-12-01 21:47:15,762 exception 118 Internal Server Error: /xadmin/user/user/add/
Traceback (most recent call last):
  File "D:\zx\Virtualenvs\lf\lib\site-packages\django\db\backends\utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\django\db\backends\mysql\base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\pymysql\connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\pymysql\connections.py", line 732, in _read_query_result
    result.read()
  File "D:\zx\Virtualenvs\lf\lib\site-packages\pymysql\connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "D:\zx\Virtualenvs\lf\lib\site-packages\pymysql\connections.py", line 684, in _read_packet
    packet.check_error()
  File "D:\zx\Virtualenvs\lf\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicate entry '' for key 'mobile'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\zx\Virtualenvs\lf\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\xadmin\sites.py", line 300, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\xadmin\sites.py", line 208, in inner
    return view(request, *args, **kwargs)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\xadmin\views\base.py", line 282, in view
    return handler(request, *args, **kwargs)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\django\utils\decorators.py", line 62, in _wrapper
    return bound_func(*args, **kwargs)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\django\utils\decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\django\utils\decorators.py", line 58, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "d:\pythonall\python3.6464\Lib\contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\xadmin\views\base.py", line 80, in method
    return filter_chain(filters, len(filters) - 1, _inner_method, *args, **kwargs)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\xadmin\views\base.py", line 49, in filter_chain
    return func()
  File "D:\zx\Virtualenvs\lf\lib\site-packages\xadmin\views\base.py", line 74, in _inner_method
    return func(self, *args, **kwargs)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\xadmin\views\edit.py", line 292, in post
    self.save_models()
  File "D:\zx\Virtualenvs\lf\lib\site-packages\xadmin\views\base.py", line 80, in method
    return filter_chain(filters, len(filters) - 1, _inner_method, *args, **kwargs)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\xadmin\views\base.py", line 49, in filter_chain
    return func()
  File "D:\zx\Virtualenvs\lf\lib\site-packages\xadmin\views\base.py", line 74, in _inner_method
    return func(self, *args, **kwargs)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\xadmin\views\edit.py", line 267, in save_models
    self.new_obj.save()
  File "D:\zx\Virtualenvs\lf\lib\site-packages\django\contrib\auth\base_user.py", line 73, in save
    super().save(*args, **kwargs)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\django\db\models\base.py", line 729, in save
    force_update=force_update, update_fields=update_fields)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\django\db\models\base.py", line 759, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\django\db\models\base.py", line 842, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\django\db\models\base.py", line 880, in _do_insert
    using=using, raw=raw)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\django\db\models\query.py", line 1125, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\django\db\models\sql\compiler.py", line 1285, in execute_sql
    cursor.execute(sql, params)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\django\db\backends\utils.py", line 100, in execute
    return super().execute(sql, params)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\django\db\backends\utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\django\db\backends\utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\django\db\backends\utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\django\db\utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\zx\Virtualenvs\lf\lib\site-packages\django\db\backends\utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\django\db\backends\mysql\base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\pymysql\connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\pymysql\connections.py", line 732, in _read_query_result
    result.read()
  File "D:\zx\Virtualenvs\lf\lib\site-packages\pymysql\connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "D:\zx\Virtualenvs\lf\lib\site-packages\pymysql\connections.py", line 684, in _read_packet
    packet.check_error()
  File "D:\zx\Virtualenvs\lf\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
django.db.utils.IntegrityError: (1062, "Duplicate entry '' for key 'mobile'")
ERROR 2019-12-01 21:47:16,434 basehttp 124 "POST /xadmin/user/user/add/ HTTP/1.1" 500 295734
INFO 2019-12-01 21:47:21,307 basehttp 124 "GET /xadmin/user/user/add/ HTTP/1.1" 200 15966
ERROR 2019-12-01 21:50:27,630 exception 118 Internal Server Error: /xadmin/user/user/add/
Traceback (most recent call last):
  File "D:\zx\Virtualenvs\lf\lib\site-packages\django\db\backends\utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\django\db\backends\mysql\base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\pymysql\connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\pymysql\connections.py", line 732, in _read_query_result
    result.read()
  File "D:\zx\Virtualenvs\lf\lib\site-packages\pymysql\connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "D:\zx\Virtualenvs\lf\lib\site-packages\pymysql\connections.py", line 684, in _read_packet
    packet.check_error()
  File "D:\zx\Virtualenvs\lf\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicate entry '' for key 'mobile'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\zx\Virtualenvs\lf\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\xadmin\sites.py", line 300, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\xadmin\sites.py", line 208, in inner
    return view(request, *args, **kwargs)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\xadmin\views\base.py", line 282, in view
    return handler(request, *args, **kwargs)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\django\utils\decorators.py", line 62, in _wrapper
    return bound_func(*args, **kwargs)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\django\utils\decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\django\utils\decorators.py", line 58, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "d:\pythonall\python3.6464\Lib\contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\xadmin\views\base.py", line 80, in method
    return filter_chain(filters, len(filters) - 1, _inner_method, *args, **kwargs)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\xadmin\views\base.py", line 49, in filter_chain
    return func()
  File "D:\zx\Virtualenvs\lf\lib\site-packages\xadmin\views\base.py", line 74, in _inner_method
    return func(self, *args, **kwargs)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\xadmin\views\edit.py", line 292, in post
    self.save_models()
  File "D:\zx\Virtualenvs\lf\lib\site-packages\xadmin\views\base.py", line 80, in method
    return filter_chain(filters, len(filters) - 1, _inner_method, *args, **kwargs)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\xadmin\views\base.py", line 49, in filter_chain
    return func()
  File "D:\zx\Virtualenvs\lf\lib\site-packages\xadmin\views\base.py", line 74, in _inner_method
    return func(self, *args, **kwargs)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\xadmin\views\edit.py", line 267, in save_models
    self.new_obj.save()
  File "D:\zx\Virtualenvs\lf\lib\site-packages\django\contrib\auth\base_user.py", line 73, in save
    super().save(*args, **kwargs)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\django\db\models\base.py", line 729, in save
    force_update=force_update, update_fields=update_fields)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\django\db\models\base.py", line 759, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\django\db\models\base.py", line 842, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\django\db\models\base.py", line 880, in _do_insert
    using=using, raw=raw)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\django\db\models\query.py", line 1125, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\django\db\models\sql\compiler.py", line 1285, in execute_sql
    cursor.execute(sql, params)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\django\db\backends\utils.py", line 100, in execute
    return super().execute(sql, params)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\django\db\backends\utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\django\db\backends\utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\django\db\backends\utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\django\db\utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\zx\Virtualenvs\lf\lib\site-packages\django\db\backends\utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\django\db\backends\mysql\base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\pymysql\connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\pymysql\connections.py", line 732, in _read_query_result
    result.read()
  File "D:\zx\Virtualenvs\lf\lib\site-packages\pymysql\connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "D:\zx\Virtualenvs\lf\lib\site-packages\pymysql\connections.py", line 684, in _read_packet
    packet.check_error()
  File "D:\zx\Virtualenvs\lf\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
django.db.utils.IntegrityError: (1062, "Duplicate entry '' for key 'mobile'")
ERROR 2019-12-01 21:50:27,826 basehttp 124 "POST /xadmin/user/user/add/ HTTP/1.1" 500 295815
WARNING 2019-12-01 22:09:19,551 base 93 Not Found: /favicon.ico
WARNING 2019-12-01 22:09:19,552 basehttp 124 "GET /favicon.ico HTTP/1.1" 404 2416
WARNING 2019-12-01 22:09:20,400 base 93 Not Found: /xadmin/user/add/
WARNING 2019-12-01 22:09:20,401 basehttp 124 "GET /xadmin/user/add/ HTTP/1.1" 404 6604
ERROR 2019-12-01 22:20:15,601 exception 9 <user.views.LoginAPIView object at 0x0000020A632BD160> - POST - Class LoginModelSerializer missing "Meta.model" attribute
ERROR 2019-12-01 22:20:15,603 basehttp 124 "POST /user/login HTTP/1.1" 500 72
ERROR 2019-12-01 22:21:49,579 exception 9 <user.views.LoginAPIView object at 0x00000245D683CA90> - POST - Class LoginModelSerializer missing "Meta.model" attribute
ERROR 2019-12-01 22:21:49,581 basehttp 124 "POST /user/login?username=zx&password=zx112143 HTTP/1.1" 500 72
ERROR 2019-12-01 22:22:31,149 exception 9 <user.views.LoginAPIView object at 0x00000245D68A1710> - POST - Class LoginModelSerializer missing "Meta.model" attribute
ERROR 2019-12-01 22:22:31,150 basehttp 124 "POST /user/login HTTP/1.1" 500 72
INFO 2019-12-01 22:24:44,098 basehttp 124 "POST /user/login HTTP/1.1" 200 216
INFO 2019-12-01 22:25:51,936 basehttp 124 "POST /user/login HTTP/1.1" 200 216
INFO 2019-12-01 22:27:19,242 basehttp 124 "POST /user/mobile HTTP/1.1" 200 42
INFO 2019-12-01 22:27:27,453 basehttp 124 "POST /user/mobile HTTP/1.1" 200 36
INFO 2019-12-01 22:27:41,554 basehttp 124 "POST /user/mobile HTTP/1.1" 200 36
INFO 2019-12-01 22:27:45,762 basehttp 124 "POST /user/mobile HTTP/1.1" 200 36
INFO 2019-12-01 22:28:37,468 basehttp 124 "POST /user/mobile HTTP/1.1" 200 39
ERROR 2019-12-01 23:12:53,806 exception 9 <user.views.SMSAPIView object at 0x0000021F800A8DD8> - POST - Method "POST" not allowed.
WARNING 2019-12-01 23:12:53,808 basehttp 124 "POST /user/sms HTTP/1.1" 405 41
ERROR 2019-12-01 23:16:22,940 exception 9 <user.views.SMSAPIView object at 0x000002036C2F7F60> - POST - Method "POST" not allowed.
WARNING 2019-12-01 23:16:22,942 basehttp 124 "POST /user/sms HTTP/1.1" 405 41
ERROR 2019-12-01 23:17:33,448 sms 26 短信发送失败：1020
INFO 2019-12-01 23:17:33,450 basehttp 124 "POST /user/sms HTTP/1.1" 200 42
INFO 2019-12-01 23:20:03,435 basehttp 124 "POST /user/sms HTTP/1.1" 200 42
INFO 2019-12-01 23:28:18,611 basehttp 124 "POST /user/sms HTTP/1.1" 200 42
ERROR 2019-12-01 23:30:17,756 exception 118 Internal Server Error: /user/login/mobile
Traceback (most recent call last):
  File "D:\zx\Virtualenvs\lf\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\rest_framework\views.py", line 507, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\rest_framework\views.py", line 422, in finalize_response
    % type(response)
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
ERROR 2019-12-01 23:30:18,213 basehttp 124 "POST /user/login/mobile HTTP/1.1" 500 86182
ERROR 2019-12-01 23:32:27,520 exception 118 Internal Server Error: /user/login/mobile
Traceback (most recent call last):
  File "D:\zx\Virtualenvs\lf\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\rest_framework\views.py", line 507, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\rest_framework\views.py", line 422, in finalize_response
    % type(response)
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
ERROR 2019-12-01 23:32:28,021 basehttp 124 "POST /user/login/mobile HTTP/1.1" 500 86183
ERROR 2019-12-01 23:33:43,861 exception 118 Internal Server Error: /user/login/mobile
Traceback (most recent call last):
  File "D:\zx\Virtualenvs\lf\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\rest_framework\views.py", line 507, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\rest_framework\views.py", line 422, in finalize_response
    % type(response)
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
ERROR 2019-12-01 23:33:44,256 basehttp 124 "POST /user/login/mobile HTTP/1.1" 500 86183
ERROR 2019-12-01 23:33:47,479 exception 118 Internal Server Error: /user/login/mobile
Traceback (most recent call last):
  File "D:\zx\Virtualenvs\lf\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\rest_framework\views.py", line 507, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\rest_framework\views.py", line 422, in finalize_response
    % type(response)
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
ERROR 2019-12-01 23:33:47,559 basehttp 124 "POST /user/login/mobile HTTP/1.1" 500 86183
ERROR 2019-12-01 23:34:45,658 exception 118 Internal Server Error: /user/login/mobile
Traceback (most recent call last):
  File "D:\zx\Virtualenvs\lf\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\rest_framework\views.py", line 507, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "D:\zx\Virtualenvs\lf\lib\site-packages\rest_framework\views.py", line 422, in finalize_response
    % type(response)
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
ERROR 2019-12-01 23:34:46,153 basehttp 124 "POST /user/login/mobile HTTP/1.1" 500 86183
INFO 2019-12-01 23:36:09,324 basehttp 124 "POST /user/login/mobile HTTP/1.1" 200 33
